const numbers = [
  [0, "٠", "صفر", "sifr"],
  [1, "١", "واحد", "wahed"],
  [2, "٢", "اتنين", "itneen"],
  [3, "٣", "تلاتة", "talata"],
  [4, "٤", "أربعة", "arba'a"],
  [5, "٥", "خمسة", "khamsa"],
  [6, "٦", "ستة", "sitta"],
  [7, "٧", "سبعة", "saba'a"],
  [8, "٨", "تمنية", "tamanya"],
  [9, "٩", "تسعة", "tes'a"],
  [10, "١٠", "عشرة", "ashara"],
  [11, "١١", "أحد عشر", "ahad 'ashar"],
  [12, "١٢", "اتنا عشر", "itna 'ashar"],
  [13, "١٣", "تلاتا عشر", "talata 'ashar"],
  [14, "١٤", "أربعة عشر", "arba'a 'ashar"],
  [15, "١٥", "خمسة عشر", "khamsa 'ashar"],
  [16, "١٦", "ستة عشر", "sitta 'ashar"],
  [17, "١٧", "سبعة عشر", "saba'a 'ashar"],
  [18, "١٨", "تمنية عشر", "tamanya 'ashar"],
  [19, "١٩", "تسعة عشر", "tes'a 'ashar"],
  [20, "٢٠", "عشرين", "ishreen"],
  [21, "٢١", "واحد وعشرين", "wahed w'ishreen"],
  [22, "٢٢", "اتنين وعشرين", "itneen w'ishreen"],
  [23, "٢٣", "تلاتة وعشرين", "talata w'ishreen"],
  [24, "٢٤", "أربعة وعشرين", "arba'a w'ishreen"],
  [25, "٢٥", "خمسة وعشرين", "khamsa w'ishreen"],
  [26, "٢٦", "ستة وعشرين", "sitta w'ishreen"],
  [27, "٢٧", "سبعة وعشرين", "saba'a w'ishreen"],
  [28, "٢٨", "تمنية وعشرين", "tamanya w'ishreen"],
  [29, "٢٩", "تسعة وعشرين", "tes'a w'ishreen"],
  [30, "٣٠", "تلاتين", "talateen"],
  [31, "٣١", "واحد وتلاتين", "wahed w'talateen"],
  [32, "٣٢", "اتنين وتلاتين", "itneen w'talateen"],
  [33, "٣٣", "تلاتة وتلاتين", "talata w'talateen"],
  [34, "٣٤", "أربعة وتلاتين", "arba'a w'talateen"],
  [35, "٣٥", "خمسة وتلاتين", "khamsa w'talateen"],
  [36, "٣٦", "ستة وتلاتين", "sitta w'talateen"],
  [37, "٣٧", "سبعة وتلاتين", "saba'a w'talateen"],
  [38, "٣٨", "تمنية وتلاتين", "tamanya w'talateen"],
  [39, "٣٩", "تسعة وتلاتين", "tes'a w'talateen"],
  [40, "٤٠", "أربعين", "arba'een"],
  [41, "٤١", "واحد وأربعين", "wahed w'arba'een"],
  [42, "٤٢", "اتنين وأربعين", "itneen w'arba'een"],
  [43, "٤٣", "تلاتة وأربعين", "talata w'arba'een"],
  [44, "٤٤", "أربعة وأربعين", "arba'a w'arba'een"],
  [45, "٤٥", "خمسة وأربعين", "khamsa w'arba'een"],
  [46, "٤٦", "ستة وأربعين", "sitta w'arba'een"],
  [47, "٤٧", "سبعة وأربعين", "saba'a w'arba'een"],
  [48, "٤٨", "تمنية وأربعين", "tamanya w'arba'een"],
  [49, "٤٩", "تسعة وأربعين", "tes'a w'arba'een"],
  [50, "٥٠", "خمسين", "khamsin"],
  [51, "٥١", "واحد وخمسين", "wahed w'khamsin"],
  [52, "٥٢", "اتنين وخمسين", "itneen w'khamsin"],
  [53, "٥٣", "تلاتة وخمسين", "talata w'khamsin"],
  [54, "٥٤", "أربعة وخمسين", "arba'a w'khamsin"],
  [55, "٥٥", "خمسة وخمسين", "khamsa w'khamsin"],
  [56, "٥٦", "ستة وخمسين", "sitta w'khamsin"],
  [57, "٥٧", "سبعة وخمسين", "saba'a w'khamsin"],
  [58, "٥٨", "تمنية وخمسين", "tamanya w'khamsin"],
  [59, "٥٩", "تسعة وخمسين", "tes'a w'khamsin"],
  [60, "٦٠", "ستين", "sittin"],
  [61, "٦١", "واحد وستين", "wahed w'sittin"],
  [62, "٦٢", "اتنين وستين", "itneen w'sittin"],
  [63, "٦٣", "تلاتة وستين", "talata w'sittin"],
  [64, "٦٤", "أربعة وستين", "arba'a w'sittin"],
  [65, "٦٥", "خمسة وستين", "khamsa w'sittin"],
  [66, "٦٦", "ستة وستين", "sitta w'sittin"],
  [67, "٦٧", "سبعة وستين", "saba'a w'sittin"],
  [68, "٦٨", "تمنية وستين", "tamanya w'sittin"],
  [69, "٦٩", "تسعة وستين", "tes'a w'sittin"],
  [70, "٧٠", "سبعين", "saba'een"],
  [71, "٧١", "واحد وسبعين", "wahed w'saba'een"],
  [72, "٧٢", "اتنين وسبعين", "itneen w'saba'een"],
  [73, "٧٣", "تلاتة وسبعين", "talata w'saba'een"],
  [74, "٧٤", "أربعة وسبعين", "arba'a w'saba'een"],
  [75, "٧٥", "خمسة وسبعين", "khamsa w'saba'een"],
  [76, "٧٦", "ستة وسبعين", "sitta w'saba'een"],
  [77, "٧٧", "سبعة وسبعين", "saba'a w'saba'een"],
  [78, "٧٨", "تمنية وسبعين", "tamanya w'saba'een"],
  [79, "٧٩", "تسعة وسبعين", "tes'a w'saba'een"],
  [80, "٨٠", "تمانين", "tamaaneen"],
  [81, "٨١", "واحد وتمانين", "wahed w'tamaaneen"],
  [82, "٨٢", "اتنين وتمانين", "itneen w'tamaaneen"],
  [83, "٨٣", "تلاتة وتمانين", "talata w'tamaaneen"],
  [84, "٨٤", "أربعة وتمانين", "arba'a w'tamaaneen"],
  [85, "٨٥", "خمسة وتمانين", "khamsa w'tamaaneen"],
  [86, "٨٦", "ستة وتمانين", "sitta w'tamaaneen"],
  [87, "٨٧", "سبعة وتمانين", "saba'a w'tamaaneen"],
  [88, "٨٨", "تمنية وتمانين", "tamanya w'tamaaneen"],
  [89, "٨٩", "تسعة وتمانين", "tes'a w'tamaaneen"],
  [90, "٩٠", "تسعين", "tes'een"],
  [91, "٩١", "واحد وتسعين", "wahed w'tes'een"],
  [92, "٩٢", "اتنين وتسعين", "itneen w'tes'een"],
  [93, "٩٣", "تلاتة وتسعين", "talata w'tes'een"],
  [94, "٩٤", "أربعة وتسعين", "arba'a w'tes'een"],
  [95, "٩٥", "خمسة وتسعين", "khamsa w'tes'een"],
  [96, "٩٦", "ستة وتسعين", "sitta w'tes'een"],
  [97, "٩٧", "سبعة وتسعين", "saba'a w'tes'een"],
  [98, "٩٨", "تمنية وتسعين", "tamanya w'tes'een"],
  [99, "٩٩", "تسعة وتسعين", "tes'a w'tes'een"],
  [100, "١٠٠", "مية", "mi'a"],
];


export default numbers;